language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareyourideapp
  apy_key:
    secure: osKrMMJp+wQnsqY8PZTO7gq7NgQffnB7W3UkVyFgchtxq/GbPpIuUCu5uvFZ4VnERnMLVCj+tJmtzuTLtz2RDgEtx+zKRimUeEay7FYk9kPXV/j1ouig4EYxTeCfr42ofLFyro04kp4/s7gmIiOhGN9/I6QUbZNKXjiYmgdtMno9scfnJJOEQikheZwCZu7RQ+sbrNJ/YhK4ZL190Nb+FxpUGbz9Xf+awG9qyOHFurVVDeqRUVetxInAxusvS/WHCL3W4VdI9RnZk566yXO9B22+w62QAX5YfwpyoZxUhsNq1XWd0Ywr2aMZ3gC3BOZwk6dDxJxMA0wMwjjOFy51LS+JONd3/fNGyS7vXbV+8oOGpC29ulrCqkwiubrzoxfmaugZXcxRpZpTUaKcML9Q29NOkNI3PEdVJ7Y9+8gc8fjt+N2/oFlHGQsJF1/q6Lw3BBTQIsiwQ5BnlNeXN1ueJapSGJhzeavkUQSPDSfPuPApdZBrBxgRlThuCH69PRX3oltOe3WapzIKXXK1LgDgdSBqUy4ZixvIfDIMlVNfqcMTVwYywB/PAcZO6kw3VpKbqKcFp/FOR48L4QkbeCH3Cvh0QqvI0sRwcyoM9kMJ1PXyGL4Ca8mmmDEOjGAwDfdqDNnV7zh7VxPV53Bjr6g8cwgVhJk4VbDQ6Z2JnMk9lQs=
