language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareyourideapp
  api_key:
    secure: UO49GGNvvjLd6uw7lCQ3aNZjN+m58X/fQsKDuuUKcfCcgPyscJDcv4TLbS7s5IE6aamn6n1ymaCiJIqgvR1FOnaQGXnVZ3aogtnK2Ocf6A5gAMcYXN+Lf7eWua6dmvTGP3rVgDKH65/voOMaJoy8lMdkSPxpvvbzoh09WpdMDlw/9yi31TYfzhA2XGbsDb8sqfExUuxDg3VtHnbmvB9CzMH2Q9hiEUGNiTCETmIEl4axpFWtjuN/pSdgq5QH4oZNoH/+QNr+efgtedqh43t2xNb3i6GP22VIPDYCg2UlFFu/3fydnLF2fOV745S6tgge+LyXqNdTxCHAQxp0nnmQUmdoSsJVEo9KSN6KkDsmD+CUtg58zFMattsKhZzA2uyZ1GD+ipK/SCwyzjzvYRXs/bbqsSeyRBgc+YIyl02Fw7XojQYn1vgPEuhCUDv/JWjf+NnsqnxUysPozHlX4J7wULaN6tziIdLeo1PeL7V8rPIBFlwbN/EizmSHHAw43InpKwoaYbogpDVaDPyvF7J97qT9fRe2CFL7GmePdkz35qCZXrjTIAsxGb933qMoEjl7HNuq50u+a/bL86806hALjxmLrBTsf8jQ3Jx+Ha43H/WvV4GQMKEvue+wcfYoZveMolPG5sGSR68rYgusB3lV7hHhNZdYllea7Qu+PgChkxk=
